# Page settings

baseURL = "https://resume-demo.bas.work/"
languageCode = "en"
title = "Christos Tsiligiannis"
enableGitInfo = false
googleAnalytics = "UA-XXXXXXX-Y"

[params]
    author = "Christos Tsiligiannis"
    description = "Resume"
    og_image = "better-software.png"
    twitterName = "@xristostsilis"
    ghRepo = "https://github.com/codewithbas/resume/"
    hugoRepo = "https://github.com/gohugoio/hugo/"

    [params.profile]
        enable = true
        name = "Christos Tsiligiannis"
        tagline = "Resume"
        avatar = "xristostsilis.jpg"

    [params.contact]
        enable = true

        location = "Patras, Greece"

        [[params.contact.list]]
        icon = "fas fa-phone-square"
        url = "tel:"
        text = "confidential"
        [[params.contact.list]]
        icon = "fas fa-envelope-square"
        url = "mailto:xristostsilis@gmail.com"
        text = "xristostsilis@gmail.com"
        [[params.contact.list]]
        icon = "fas fa-globe"
        url = "https://bas.bio"
        text = "My links on the web"


    [params.skills]
        enable = true

        [[params.skills.list]]
        title = "Python"
        [[params.skills.list]]
        title = "C"
        [[params.skills.list]]
        title = "Html, CSS, JS, NodeJS"


    [params.education]
        enable = true

        [[params.education.list]]
        degree = "Master of Electrical and Computer Engineering"
        university = "University of Patras"
        dates = "2016-2023"


    [params.awards]
        enable = false

        [[params.awards.list]]
        name = "Professional Scrum Master™ I"
        body = "scrum.org"
        date = "2018"


    [params.languages]
        enable = true

        [[params.languages.list]]
        name = "Greek"
        level = "Fluent"

        [[params.languages.list]]
        name = "English"
        level = "Fluent"


    [params.interests]
        enable = true

        [[params.interests.list]]
        name = "Travelling"


    [params.summary]
        enable = true
        text = "I am the guy your grandma calls when something needs fixing"


    [params.experience]
        enable = true

        [[params.experience.list]]
        title = "job"
        dates = "2020 - Present"
        company = "Bavaria"
        details = "Sales, program manager"
        [[params.experience.list.items]]
        details = "Excelence in Solar equipment"



    [params.projects]
        enable = true

        [[params.projects.list]]
        title = "5g Router"
        meta = "GitHub project"
        url = "https://github.com/codewithbas/resume"
        tagline = "A resume with a free PDF generator"


    [params.information]
        enable = true

        [[params.information.list]]
        title = "Thesis"
        [[params.information.list.items]]
        details = "5G"
        [[params.information.list.items]]
        details = "Connecting Greek motorways via 5G"

        [[params.information.list]]
        title = "Interests"
        details = "Cooking, Swimming, Cycling"

    [params.social]
        enable = true

        [[params.social.list]]
        icon = "fab fa-github-square"
        url = "https://github.com/xristostsilis"
        title = "/xristostsilis"
        [[params.social.list]]
        icon = "fab fa-linkedin"
        url = "https://linkedin.com/in/xristostsilis"
        title = "/in/xristostsilis"
        [[params.social.list]]
        icon = "fab fa-twitter-square"
        url = "https://twitter.com/xristostsilis"
        title = "@xristostsilis"
